"""Add debt_id to transactions table

Revision ID: 14a8c4906742
Revises: f7a1abfb9b3d
Create Date: 2025-07-20 15:57:33.304262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a8c4906742'
down_revision: Union[str, Sequence[str], None] = 'f7a1abfb9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('debt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'debt_accounts', ['debt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'debt_id')
    # ### end Alembic commands ###
