"""Create DebtAccount and InvestmentAccount tables

Revision ID: f7a1abfb9b3d
Revises: 49aa4cb0585d
Create Date: 2025-07-20 11:48:33.914032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a1abfb9b3d'
down_revision: Union[str, Sequence[str], None] = '49aa4cb0585d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
